.PHONY: clean All

All:
	@echo "----------Building project:[ c-test - Release ]----------"
	@cd "c-test" && "$(MAKE)" -f  "c-test.mk"
clean:
	@echo "----------Cleaning project:[ c-test - Release ]----------"
	@cd "c-test" && "$(MAKE)" -f  "c-test.mk" clean

